version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: isma
      MONGO_INITDB_ROOT_PASSWORD: isma
    networks:
      - tienda-network

  admin:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: isma
      ME_CONFIG_MONGODB_ADMINPASSWORD: isma
      ME_CONFIG_MONGODB_URL: mongodb://isma:isma@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
    networks:
      - tienda-network

  web:
    build: .
    container_name: tienda-web
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      MONGO_URI: mongodb://isma:isma@db:27017/tienda?authSource=admin
      SECRET_KEY: ElArzobispoDeConstantiplaSufreDeHipopotomonstrosesquipedaliofobiaDebidoASuAcidoDesoxirribonucleico
      FLASK_DEBUG: 1
    depends_on:
      - db
    networks:
      - tienda-network

volumes:
  mongodb_data:

networks:
  tienda-network:
    driver: bridge